- hosts: webserver
  tasks:
      - name: install python-docker ubuntu
        apt:
            name: python-docker
            state: present
        when:
           - ansible_distribution == "ubuntu"
      - name: install python-docker CentOS
        yum:
            name: python-docker
            state: present
        when:
           - ansible_distribution == "CentOS"
      - name: run container
        docker-container:
            name: container
            detach: yes
            image: "robertobatam/httpd:1"
            state: started
            exposed_ports:
              -80/tcp
            publishd_ports:
              -8085:80
